### ISSUE TITLE
Mobile version for iPhone 5 is broken

### ISSUE THREAD

**Issue by lottebijlsma** [lottebijlsma/lottebijlsma.github.io#48]

**Comment by thibmaek** [comment]
Is this still a thing? Otherwise close it please

**Comment by lottebijlsma** [comment]
Can't tell. It shouldn't be, because I tested it with the dev tools. But it wasn't a problem before in the dev tools as well. So I need an iPhone 5 to test it on. Don't know why. @thibmaek

**Comment by thibmaek** [comment]
This is how it looks now, guessing this issue can be closed since everything looks fine?
![gitscout-image-from-clipboard-1](http://static.gitscout.com/408ff086251998cb50970283964821f5106e33b7d41ac62e2d1d5a058435f241.png)
![gitscout-image-from-clipboard-2](http://static.gitscout.com/bc32fa15cb3e4ce4a38184ec69feda398828c068bd557e816afb2d398160bd9a.png)
![gitscout-image-from-clipboard-3](http://static.gitscout.com/17dddf72bd3a3d7caf84fb158625a117f1891c30875148c3a21b3fa414d5a43b.png)

**Comment by lottebijlsma** [comment]
Yes! 💯
